version: "3.8"

services:

  nfeimport:
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: ./PROD/Dockerfile
    container_name: ct_python
    hostname: ct_python
    command: watch -n 120 python /nfeimport/NFeImport.py xml/
    volumes:
      - $PWD/xml:/nfeimport/xml:rw
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
