version: "3.8"

services:

  nfeimport:
    stdin_open: true
    tty: true
    image: nfeimport

  database:
    stdin_open: true
    tty: true
    image: mariadb:latest
    container_name: ct_database
    hostname: ct_database
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - "MYSQL_ROOT_PASSWORD=123mudar"
      # - "MYSQL_USER=nfeuser"
      # - "MYSQL_PASSWORD=123mudar"
      # - "MYSQL_DATABASE=ICMS_DEV"
    volumes:
      # - "/usercode/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - $PWD/SQL_DDL/:/docker-entrypoint-initdb.d
      - $PWD/infra/database/mysql:/var/lib/mysql:rw
      - $PWD/infra/database/log:/var/log/mysql:rw
    ports:
      - 3306:3306
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
   
