version: "3.8"

services:

  nfeimport:
    stdin_open: true
    tty: true
    container_name: ${CONTAINER}
    hostname: ${PROJECT_NAME}
    # env_file:
    #   - docker.env
    # image: ${IMAGE}
    image: ${DOCKER_USER}/${PROJECT_NAME}:${DOCKER_TAG}
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
      # target: base
    # command: /nfeimport/NFeRun.sh
    restart: always
    volumes:
      - $PWD/xml:/nfeimport/xml:rw
    networks:
      - infra
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"

networks:
  infra:
    driver: bridge