name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest linux/arm/v7

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make build
